/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import br.com.DBConnection.MySqlConnection;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

public class LoginMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginMenu
     */
    public LoginMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtUser = new javax.swing.JTextField();
        jtPassword = new javax.swing.JPasswordField();
        jbJoin = new javax.swing.JButton();
        jbShowPassword = new javax.swing.JButton();
        jlLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));

        jtUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtUser.setToolTipText("Insira o nome de usuário.");
        jtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUserActionPerformed(evt);
            }
        });
        jtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtUserKeyPressed(evt);
            }
        });

        jtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtPassword.setToolTipText("Insira a senha.");
        jtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPasswordKeyPressed(evt);
            }
        });

        jbJoin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbJoin.setText("Entrar");
        jbJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJoinActionPerformed(evt);
            }
        });

        jbShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closed_eye.png"))); // NOI18N
        jbShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowPasswordActionPerformed(evt);
            }
        });

        jlLogin.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogin.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtUser, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbJoin, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jtPassword))
                        .addGap(18, 18, 18)
                        .addComponent(jbShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlLogin)
                .addGap(18, 18, 18)
                .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbJoin)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public String connectDB(){
        String user = jtUser.getText();
        String password = jtPassword.getText();
        
        if(MySqlConnection.login(user, password)){
            Connection connection = MySqlConnection.getMySqlConnection();
            if(connection!=null){
               JOptionPane.showMessageDialog(null, "Conectado com sucesso!");
               new SystemMenu().setVisible(true);
               this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Não foi possível conectar!");
            }
            return MySqlConnection.status;
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!");
            return MySqlConnection.status;
        }
    }
    
    private void jtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUserKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtPassword.requestFocus();
        }
    }//GEN-LAST:event_jtUserKeyPressed
    
    
    private void jtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            connectDB();
        }
    }//GEN-LAST:event_jtPasswordKeyPressed

    private void jbJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJoinActionPerformed
        connectDB();
    }//GEN-LAST:event_jbJoinActionPerformed

    boolean clicked = false;
    
    private void jbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowPasswordActionPerformed
        if(clicked == false){
            jtPassword.setEchoChar((char) 0);
            jbShowPassword.setIcon(new ImageIcon("src/img/opened_eye.png"));
            clicked = true;
        }
        else{
            jtPassword.setEchoChar('*');
            jbShowPassword.setIcon(new ImageIcon("src/img/closed_eye.png"));
            clicked = false;
        }
    }//GEN-LAST:event_jbShowPasswordActionPerformed

    private void jtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUserActionPerformed
   
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbJoin;
    private javax.swing.JButton jbShowPassword;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JPasswordField jtPassword;
    private javax.swing.JTextField jtUser;
    // End of variables declaration//GEN-END:variables
}
